export const jobTypes = {
	SAVE_CURRENT_JOB: 'SAVE_CURRENT_JOB',
	SAVE_ALL_JOBS: 'SAVE_ALL_JOBS',
	DELETE_CURRENT_JOB: 'DELETE_CURRENT_JOB',
}

export const userTypes = {
	LOGGED_IN: 'LOGGED_IN',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	LOGGED_OUT: 'LOGGED_OUT',
}
